apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeonta-bot-v2
  labels:
    app: pokeonta-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeonta-bot
  template:
    metadata:
      labels:
        app: pokeonta-bot
    spec:
      containers:
        - name: pokeonta-bot-v2
          image: zzmmrmn/pokeonta-bot:<IMAGE_VERSION>
          env:
            - name: PRODUCTION_BOT
              value: "PRODUCTION"
            - name: "DISCORD_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: discord.token
                  key: token
