apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeonta-bot-v2
  labels:
    app: pokeonta-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeonta-bot
  template:
    metadata:
      labels:
        app: pokeonta-bot
    spec:
      containers:
        - name: pokeonta-bot-v2
          image: zzmmrmn/pokeonta-bot:<IMAGE_VERSION>
          env:
            - name: PRODUCTION_BOT
              value: "PRODUCTION"
            - name: "DISCORD_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: discord.token
                  key: token
            - name: "DB_HOST"
              value: "private-personal-postgres-cluster-1-apr-26-backup-do-user-87772.a.db.ondigitalocean.com"
            - name: "DB_PORT"
              value: "25061"
            - name: "DB_USER"
              value: "pokeonta"
            - name: "DB_NAME"
              value: "pokeonta"
            - name: "BOT_IMAGE_VERSION"
              value: "<IMAGE_VERSION>"
            - name: "DB_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
